version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5555:5555
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - nguyen
networks:
  nguyen: